# Generated by Django 3.0 on 2020-07-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crawler.Platform', verbose_name='Channel')),
            ],
        ),
    ]
