# Generated by Django 3.0 on 2020-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='channels',
            new_name='channel',
        ),
    ]
