# Generated by Django 3.0 on 2020-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0005_auto_20200701_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='resource',
            field=models.ManyToManyField(to='Crawler.Channel', verbose_name='Resource'),
        ),
    ]
