# Generated by Django 2.1.15 on 2020-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CR_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=1000)),
                ('res_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CRId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('res_ID', models.CharField(max_length=200)),
            ],
        ),
    ]
