# Generated by Django 2.1.15 on 2020-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRId2',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('res_ID', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
